version: "3.7"
services:
    prometheus:
        image: prom/prometheus
        command: --config.file=/etc/prometheus/prometheus.yml
        ports:
            - "9090:9090"
        volumes:
            - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml
    grafana:
        image: grafana/grafana
        ports:
            - "3000:3000"
