apiVersion: v1
kind: PersistentVolume
metadata:
  name: superset-volume
  labels:
    type: local
    app: rebios-superset
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/superset


