apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: superset-data
#spec:
#  resources:
#    requests:
#      storage: 10Gi
#  volumeMode: Filesystem
#  accessModes:
#    - ReadWriteOnce
#  storageClassName: nfs
spec:
  storageClassName: manual
  volumeName: superset-volume
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
        
