apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-superset-secret
spec:
  type: kv-v2
  # Mount path of the secrets backend
  mount: tkg-des
  # Path to the secret
  path: rebios/superset
  # Where to store the secrets, end user will create the secret
  destination:
    create: true
    name: superset-password