version: "3.7"
services:
    prometheus:
        image: prom/prometheus
        user: root
        restart: always
        command: --config.file=/etc/prometheus/prometheus.yml
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
            - ../../observability/prometheus:/prometheus

    grafana:
        image: grafana/grafana
        restart: always
        ports:
            - "3000:3000"
