version: "3.7"
services:
    postgres:
        build:
            context: .
            dockerfile: postgres.dockerfile
        container_name: iceberg_postgres_db
        environment:
            - POSTGRES_PASSWORD=23mJzsfUfUJqujYc!
        volumes:
            - ../../iceberg/postgres/data:/var/lib/postgresql/data
        ports:
            - "5420:5432"
    pgAdmin:
        image: dpage/pgadmin4
        user: root
        restart: unless-stopped
        container_name: rebios-pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
            PGADMIN_DEFAULT_PASSWORD: admin
            GUNICORN_ACCESS_LOGFILE: /dev/null
        volumes:
            - ../../iceberg/pgadmin/var:/var/lib/pgadmin
        ports:
            - 9220:80
        depends_on:
            - postgres
