FROM apache/airflow:2.10.2
USER root


RUN apt-get update \
    && apt-get install -y software-properties-common


# Install OpenJDK-11
RUN apt update && \
    apt-get install -y openjdk-17-jdk && \
    apt-get install -y ant && \
    apt-get clean;

# Set JAVA_HOME
ENV JAVA_HOME  /usr/lib/jvm/java-17-openjdk-amd64/
RUN export JAVA_HOME

USER airflow

USER airflow

COPY ./requirements.txt /
RUN pip install -r /requirements.txt

COPY --chown=airflow:root ./dags /opt/airflow/dags
