kind: Deployment
apiVersion: apps/v1
metadata:
  name: spark-master
  namespace: rebios-spark
spec:
  replicas: 1
  selector:
    matchLabels:
      component: spark-master
  template:
    metadata:
      labels:
        component: spark-master
    spec:
      containers:
        - name: spark-master
          image: tabulario/spark-iceberg
            #image : jrosses/rebios-spark:1.0.0
          envFrom:
            - configMapRef:
                name: rebios-spark-master-secret
          resources:
            requests:
              memory: "8Gi"
            limits:
              memory: "20Gi"
          command:
          - /bin/sh
          - -c
          - |
            cp /tmp/postgresql-42.6.0.jar /opt/spark/jars
            chmod +x /tmp/start-spark-thrift.sh
            /tmp/start-spark-thrift.sh
            tail -f /dev/null
          ports:
            - containerPort: 7077
            - containerPort: 8080
          volumeMounts:
            - mountPath: /tmp
              name: sparkdata
      volumes:
        - name: sparkdata
          persistentVolumeClaim:
            claimName: spark-volume-claim

