apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-volume
  labels:
    type: local
    app: rebios-spark
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/spark
