kind: Service
apiVersion: v1
metadata:
  name: spark-worker
  namespace: rebios-spark
spec:
  type: NodePort
  ports:
    - name: webui
      port: 7890
      targetPort: 8080
      nodePort: 30011
    - name: spark
      port: 7077
      targetPort: 7077
      nodePort: 30012
    - name: hive
      port: 10000
      targetPort: 10000
      nodePort: 30013
  selector:
    component: spark-worker

