apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-volume-claim
  labels:
    app: rebios-spark
spec:
  storageClassName: manual
  volumeName: spark-volume
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

