version: "3.7"
services:
    hue:
        build:
            context: .
            dockerfile: hue.dockerfile
        platform: linux/amd64
#        image: gethue/hue:latest
        container_name: hue_server
        ports:
            - "8888:8888"
        volumes:
            - ./config/hue.ini:/usr/share/hue/desktop/conf/hue.ini
            - ./config/log.conf:/etc/hue/conf/log.conf
        deploy:
            resources:
               limits:
                  cpus: '2'
                  memory: 4G
               reservations:
                  cpus: '1'
                  memory: 2G              
        extra_hosts:
            - host.docker.internal:host-gateway
